### ISSUE TITLE
Type: "a Hello directly from (your country) <3 "

### ISSUE THREAD

**Issue by Max-Wendel-UFC** [Max-Wendel-UFC/MyAntBuild#4]
Insert on Readme.md :smile_cat: 

[(your name)] - (profile link) - (Hello mensage)

_For example:
 [Max Wendel](https://github.com/Max-Wendel-UFC) - Hello from Brazil_ :brazil: !!!

**Comment by Hematophagus** [comment]
[Gabriel] - github.com/Hematophagus - Hello from Brazil?

**Comment by imedqq** [comment]
Hello, I would like to work on this! :^)
